kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        audit-log-path: /var/log/kubernetes/audit/audit.log
        audit-log-maxage: "7"
        audit-log-maxbackup: "5"
        audit-log-maxsize: "100"
        audit-policy-file: /etc/kubernetes/audit/audit-policy.yaml
      extraVolumes:
      - name: audit-logs
        hostPath: /var/log/kubernetes/audit
        mountPath: /var/log/kubernetes/audit
        readOnly: false
        pathType: DirectoryOrCreate
      - name: audit-policy
        hostPath: /etc/kubernetes/audit
        mountPath: /etc/kubernetes/audit
        readOnly: true
        pathType: DirectoryOrCreate
