apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-terminating
spec:
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: Exists
  weight: 100
  delay:
    durationMilliseconds: 2000
    jitterDurationMilliseconds: 500
  next:
    event:
      type: Normal
      reason: DeletingNode
      message: "Node is being deleted"
    statusTemplate: |
      {{ $now := Now }}
      conditions:
      {{ range NodeConditions }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $now | Quote }}
        message: "Node is terminating"
        reason: "NodeTerminating"
        status: "False"
        type: {{ .type | Quote }}
      {{ end }}
      phase: Terminating
