apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-delete
spec:
  delay:
    durationMilliseconds: 5000
    jitterDurationMilliseconds: 1000
  next:
    event:
      type: Normal
      reason: Killing
      message: "Stopping container"
    delete: true
    finalizers:
      empty: true
    statusSubresource: status
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: Exists
  weight: 100
