apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-container-events
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: DoesNotExist
    - key: .status.phase
      operator: In
      values:
      - "Running"
    - key: '.status.conditions.[] | select( .type == "Ready" ) | .status'
      operator: In
      values:
      - "True"
  weight: 2
  delay:
    durationMilliseconds: 500
  next:
    event:
      type: Normal
      reason: Started
      message: "Started container"
