kind: Cluster
apiVersion: kind.x-k8s.io/v1beta3
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
          - name: authorization-mode
            value: AlwaysAllow