kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    scheduler:
      extraArgs:
        authentication-tolerate-lookup-failure: "false"
        authorization-always-allow-paths: "/healthz,/readyz,/livez,/metrics"
        bind-address: "0.0.0.0"
        secure-port: "10259"
        v: "2"
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authentication-token-webhook: "true"
        authorization-mode: "Webhook"
  - |
    kind: KubeletConfiguration
    authentication:
      webhook:
        enabled: true
    authorization:
      mode: Webhook
featureGates:
  PodTopologySpread: true
  DefaultPodTopologySpread: true
