simulator:
  run_id: k8s_scenario_1753908801
  run_description: Generated Kubernetes scenario with 3 deployments
  associated_scenario: k8s_scenario_1753908801
  timestep: 15
  start_step: 1
  limit: 60
  instance_pool_size: 1000
  logging: 1
  clusters:
  - KubernetesCluster:
      type: KubernetesCluster
      name: default
      node_count: 3
      node_type: c5.large
      autoscaling: true
      nodepool_directory: nodepools


  deployments_directory: deployments
  deployments:
  - deploy-if
  - deploy-ov
  - deploy-h0
