apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - name: kube-scheduler
    command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --config=/etc/kubernetes/scheduler-config.yaml
    volumeMounts:
    - name: scheduler-config
      mountPath: /etc/kubernetes/scheduler-config.yaml
      subPath: scheduler-config.yaml
      readOnly: true
  volumes:
  - name: scheduler-config
    hostPath:
      path: /patches/scheduler-config.yaml
      type: File
