name: kind-e2e
on:
  # enable running this on merges + presubmits when the action has tests that it will execute
  # push:
  #   branches: [main]
  # pull_request:
  workflow_dispatch:
jobs:
  test-kind:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8sVersion: ["1.23.x", "1.24.x", "1.25.x", "1.26.x", "1.27.x", "1.28.x", "1.29.x", "1.30.x"]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: ./.github/actions/install-deps
      with:
          k8sVersion: ${{ matrix.k8sVersion }}
    - name: Kind Cluster
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
    - name: check kind cluster and taint nodes
      shell: bash
      run: |
        kubectl config current-context
        kubectl get nodes
        kubectl taint nodes chart-testing-control-plane CriticalAddonsOnly:NoSchedule
    - name: install prometheus 
      uses: ./.github/actions/install-prometheus
    - name: install pyroscope 
      uses: ./.github/actions/install-pyroscope
    - name: install kwok and controller
      shell: bash
      run: |
        make toolchain
        make install-kwok
        @git diff || { echo "New file modification detected in the Git working tree. Please check in before commit."; git --no-pager diff --name-only | uniq | awk '{print "  - " $$0}'; if [ "${CI}" = true ]; then exit 1; fi;}
        KWOK_REPO=kind.local KIND_CLUSTER_NAME=chart-testing make apply-with-kind
    - name: ping cluster
      shell: bash
      run: | 
        kubectl get pods -n kube-system | grep karpenter 
        kubectl get nodepools
        kubectl get pods -A
        kubectl describe nodes
    - uses: actions/checkout@v4
      with:
        repository: nathangeology/karpenter_evaluate
        path: ./karpenter_eval/ # Installs to a folder in the Karpenter repo for the test
    - name: install KPI report dependencies
      shell: bash
      run: |
        pip install pandas
        pip install prometheus-api-client
        pip install ./karpenter_eval/
    - name: run test suites
      shell: bash
      run: |
        export e2e_test_output=$(make e2etests | tail -n 50)
        line=$(echo "$e2e_test_output" | grep "Printed CSV TO")
        directory=$(echo "$line" | sed -E 's|.*Printed CSV TO (/tmp/[0-9]+).*|\1|')
        export TEMP_DIR="$directory"
        echo "The KPI milestones data is in $TEMP_DIR"
    - name: run KPI report
      shell: bash
      run: |
        echo "run KPIs here"
        python ./karpenter_eval/main.py "$TEMP_DIR"
    - name: cleanup 
      shell: bash
      run: | 
        kubectl delete nodepools --all 
        make delete
        make uninstall-kwok
        