name: kind-e2e
on:
  # enable running this on merges + presubmits when the action has tests that it will execute
  # push:
  #   branches: [main]
  # pull_request:
  workflow_dispatch:
jobs:
  test-kind:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8sVersion: ["1.23.x", "1.24.x", "1.25.x", "1.26.x", "1.27.x", "1.28.x", "1.29.x", "1.30.x"]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Python 3.10
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1
      with:
        python-version: "3.10"
    - uses: ./.github/actions/install-deps
      with:
          k8sVersion: ${{ matrix.k8sVersion }}
    - name: Kind Cluster
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
    - name: check kind cluster and taint nodes
      shell: bash
      run: |
        kubectl config current-context
        kubectl get nodes
        kubectl taint nodes chart-testing-control-plane CriticalAddonsOnly:NoSchedule
    - name: install prometheus 
      uses: ./.github/actions/install-prometheus
    - name: install pyroscope 
      uses: ./.github/actions/install-pyroscope
    - name: install kwok and controller
      shell: bash
      run: |
        make toolchain
        make install-kwok
        export KWOK_REPO=kind.local
        export KIND_CLUSTER_NAME=chart-testing
        make apply-with-kind
    - name: ping cluster
      shell: bash
      run: | 
        sleep 15
        kubectl get pods -n kube-system | grep karpenter 
        kubectl get nodepools
        kubectl get pods -A
        kubectl describe nodes
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        repository: nathangeology/karpenter_evaluate
        ref: main/42340d4
        fetch-depth: 0
        path: ./karpenter_eval/ # Installs to a folder in the Karpenter repo for the test
    - name: install KPI report dependencies
      shell: bash
      run: |
        pip install awswrangler
        pip install tabulate
        pip install prometheus-api-client
        pip install ./karpenter_eval/
    - name: run test suites
      shell: bash
      run: |
        e2e_test_output=$(make e2etests | tail -n 50)
        export e2e_test_output
        line=$(echo "$e2e_test_output" | grep "Printed CSV TO")
        directory=$(echo "$line" | sed -E 's|.*Printed CSV TO (/tmp/[0-9]+).*|\1|')
        TEMP_DIR="$directory"
        export TEMP_DIR
        echo "The KPI milestones data is in $TEMP_DIR"
        echo "run KPIs here"
        python ./karpenter_eval/main.py
    - name: cleanup 
      shell: bash
      run: | 
        kubectl delete nodepools --all 
        make delete
        make uninstall-kwok
        